spring:
  datasource:
    url: db
    username: db
    password: db
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    platform: MS-SQL

  mybatis:
    config-location: classpath:mybatis-config.xml