spring:
  datasource:
    url: db
    username: db #数据库链接
    password: db
    driver-class-name: oracle.jdbc.OracleDriver
    platform: oracle

  mybatis:
    config-location: classpath:mybatis-config.xml